Fixes immediate closing bug
codidact/co-design pull request #73
Opened 2022-09-14 03:07 UTC by MoshiKoi

Fixes #72

2022-09-14 13:14 UTC, ArtOfCode- requested changes
This reverts `package-lock.json` back to version 1 and removes all the package specifications. The code is good to go, but can we either re-update package-lock or exclude it from this PR?

2022-11-26 08:36 UTC, Taeir approved these changes

2022-11-26 08:37 UTC, Taeir commented
@ArtOfCode- Your requested changes were made, could you merge this?

2022-11-26 08:38 UTC, merged

2022-11-26 08:38 UTC, ArtOfCode- commented
@Taeir done, thanks for the reminder!